"""Tests for B2 — webhook signature validation + AI origin detection."""
import hashlib
import hmac
import json

import pytest

from app.config import settings
from app.webhook.ai_detector import detect_ai_origin


def _make_signature(body: bytes) -> str:
    sig = hmac.new(settings.github_webhook_secret.encode(), body, hashlib.sha256).hexdigest()
    return f"sha256={sig}"


# ── Signature tests ──────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_webhook_rejects_bad_signature(client):
    payload = json.dumps({"action": "opened"}).encode()
    resp = await client.post(
        "/webhook/github",
        content=payload,
        headers={
            "X-GitHub-Event": "pull_request",
            "X-Hub-Signature-256": "sha256=badsignature",
            "Content-Type": "application/json",
        },
    )
    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_webhook_accepts_valid_signature(client):
    payload = json.dumps({"action": "labeled", "pull_request": {}}).encode()
    sig = _make_signature(payload)
    resp = await client.post(
        "/webhook/github",
        content=payload,
        headers={
            "X-GitHub-Event": "pull_request",
            "X-Hub-Signature-256": sig,
            "Content-Type": "application/json",
        },
    )
    # "labeled" is not in allowed actions — should be ignored, not error
    assert resp.status_code == 200
    assert resp.json()["status"] == "ignored"


# ── AI detector unit tests ───────────────────────────────────────────────────

def test_ai_detector_bot_sender():
    result = detect_ai_origin({
        "pull_request": {"title": "add feature", "body": ""},
        "sender": {"login": "github-actions[bot]"},
    })
    assert result["is_ai"] is True
    assert "bot-sender-login" in result["signals"]


def test_ai_detector_clean_pr():
    result = detect_ai_origin({
        "pull_request": {"title": "fix: typo in readme", "body": "Small fix"},
        "sender": {"login": "prakhar"},
    })
    assert result["is_ai"] is False
    assert result["confidence"] < 0.4


def test_ai_detector_codex_title():
    result = detect_ai_origin({
        "pull_request": {
            "title": "Generated by Codex: add auth middleware",
            "body": "",
        },
        "sender": {"login": "prakhar"},
    })
    assert result["is_ai"] is True
    assert "ai-keyword-in-title-or-body" in result["signals"]
