"""
AI origin detection — determines if a PR was likely AI-generated.

Signals checked:
1. Commit message patterns  (Codex, Claude, Copilot keywords)
2. Co-authored-by trailer   (common in AI-assisted commits)
3. Statistical fingerprinting (uniform line length, low comment density)
"""
import re
import statistics
from typing import Any

# Patterns found in AI-generated commit messages
_AI_MSG_PATTERNS = [
    r"generated by (codex|claude|copilot|devin|cursor)",
    r"co-authored-by:.*bot",
    r"\[codex\]",
    r"\[ai\]",
    r"feat(\(.+\))?!?:.*\(ai\)",
    r"automated (commit|change|refactor)",
]
_AI_REGEX = re.compile("|".join(_AI_MSG_PATTERNS), re.IGNORECASE)


def detect_ai_origin(payload: dict[str, Any]) -> dict[str, Any]:
    """
    Returns:
        {
            "is_ai": bool,
            "confidence": float,   # 0.0 – 1.0
            "signals": list[str],
        }
    """
    signals: list[str] = []
    score = 0.0

    pr = payload.get("pull_request", {})
    commits_url = pr.get("commits_url", "")  # used externally if needed

    # Signal 1 — PR title / body keywords
    title: str = pr.get("title", "")
    body: str = pr.get("body", "") or ""
    if _AI_REGEX.search(title) or _AI_REGEX.search(body):
        signals.append("ai-keyword-in-title-or-body")
        score += 0.5

    # Signal 2 — head commit message
    head_commit_msg: str = (
        payload.get("head_commit", {}) or {}
    ).get("message", "")
    if _AI_REGEX.search(head_commit_msg):
        signals.append("ai-keyword-in-commit-message")
        score += 0.4

    # Signal 3 — sender login patterns (bot accounts)
    sender: str = payload.get("sender", {}).get("login", "")
    if sender.endswith("[bot]") or "codex" in sender.lower():
        signals.append("bot-sender-login")
        score += 0.6

    # Signal 4 — statistical fingerprinting on diff patch lines
    patch_lines: list[str] = []
    for file_obj in payload.get("_diff_files", []):
        patch = file_obj.get("patch", "") or ""
        patch_lines += [
            ln[1:] for ln in patch.splitlines()
            if ln.startswith("+") and not ln.startswith("+++")
        ]

    if patch_lines:
        # Uniform line length is a weak AI signal
        lengths = [len(l) for l in patch_lines if l.strip()]
        if lengths:
            try:
                stdev = statistics.stdev(lengths)
                if stdev < 8:  # suspiciously uniform
                    signals.append("uniform-line-length")
                    score += 0.15
            except statistics.StatisticsError:
                pass

        # Very low comment density
        comment_lines = sum(
            1 for l in patch_lines
            if l.strip().startswith(("#", "//", "/*", "*", "<!--"))
        )
        density = comment_lines / max(len(patch_lines), 1)
        if density < 0.01 and len(patch_lines) > 20:
            signals.append("low-comment-density")
            score += 0.1

    confidence = min(round(score, 2), 1.0)
    return {
        "is_ai": confidence >= 0.4,
        "confidence": confidence,
        "signals": signals,
    }
