"use client";

import { motion } from "framer-motion";
import { Database, ShieldAlert, GitMerge, Brain, Activity } from "lucide-react";

const features = [
  {
    title: "Qdrant Memory Engine",
    desc: "Uses vector search to instantly compare new PR diffs against past architectural decisions, spotting contradictions before they merge.",
    icon: Database,
    color: "text-blue-400",
  },
  {
    title: "Groq LLM Reasoning",
    desc: "Utilizes llama-3.3-70b-versatile to generate human-readable explanations of why a PR violates repository rules.",
    icon: Brain,
    color: "text-purple-400",
  },
  {
    title: "AST Security Analysis",
    desc: "Parses code structurally to detect SQL injections, hardcoded secrets, and unsafe deserialization.",
    icon: ShieldAlert,
    color: "text-red-400",
  },
  {
    title: "Blast Radius Detection",
    desc: "Builds a real-time dependency graph to understand exactly how many files a single change will impact.",
    icon: Activity,
    color: "text-emerald-400",
  },
  {
    title: "AI Origin Detection",
    desc: "Statistically analyzes commits to detect code generated by bots like Devin or Copilot, applying stricter safety gates.",
    icon: GitMerge,
    color: "text-orange-400",
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.1, delayChildren: 0.6 }
  }
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { type: "spring" as const, stiffness: 100 } }
};

export default function FeatureCards() {
  return (
    <section className="py-20 w-full max-w-6xl mx-auto">
      <div className="text-center mb-16">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">A 5-Layer Defense System</h2>
        <p className="text-zinc-400 max-w-2xl mx-auto">Built from the ground up to handle the volume and unpredictability of agentic coding pipelines.</p>
      </div>

      <motion.div 
        variants={containerVariants}
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-100px" }}
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
      >
        {features.map((feature, idx) => {
          const Icon = feature.icon;
          return (
            <motion.div 
              key={idx}
              variants={itemVariants}
              className="glass-panel p-6 rounded-2xl group hover:border-brand-primary/50 transition-colors duration-300"
            >
              <div className={`w-12 h-12 rounded-xl bg-brand-surface border border-brand-surface-border flex items-center justify-center mb-6 group-hover:scale-110 transition-transform ${feature.color}`}>
                <Icon className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
              <p className="text-zinc-400 leading-relaxed text-sm">
                {feature.desc}
              </p>
            </motion.div>
          );
        })}
      </motion.div>
    </section>
  );
}
