"use client";

import { useEffect, useRef, useState } from "react";
import { Shield, Brain, Activity, Database, GitMerge, Lock } from "lucide-react";

const LAYERS = [
  {
    number: "01",
    title: "AST Security Analysis",
    desc: "Parses every changed file into its Abstract Syntax Tree using tree-sitter. Detects SQL injection, hardcoded secrets, auth bypass patterns, and unsafe eval usage at the structural level — not just regex.",
    icon: Shield,
    accent: "#ef4444",
    glow: "rgba(239,68,68,0.15)",
    tag: "CRITICAL DETECTION",
  },
  {
    number: "02",
    title: "Architectural Memory",
    desc: "Embeds every PR decision into a Qdrant vector database. When new AI code arrives, semantic search finds contradictions against past architectural rules — even if worded completely differently.",
    icon: Brain,
    accent: "#8b5cf6",
    glow: "rgba(139,92,246,0.15)",
    tag: "QDRANT VECTORS",
  },
  {
    number: "03",
    title: "Blast Radius Engine",
    desc: "Builds a real-time dependency graph with NetworkX betweenness centrality. A single-line change in a shared utility that 40 services import? Flagged immediately, mandatory human review.",
    icon: Activity,
    accent: "#f59e0b",
    glow: "rgba(245,158,11,0.15)",
    tag: "NETWORKX GRAPH",
  },
  {
    number: "04",
    title: "Rejected Pattern Memory",
    desc: "Maintains a searchable index of patterns explicitly rejected in past code reviews. AI agents repeat the same mistakes. VaultCI surfaces the original rejection with who rejected it, why, and when.",
    icon: Lock,
    accent: "#f97316",
    glow: "rgba(249,115,22,0.15)",
    tag: "PERSISTENT INDEX",
  },
  {
    number: "05",
    title: "AI Origin Detection",
    desc: "Statistically fingerprints commits to detect code generated by Codex, Claude, or Devin via co-author tags, commit message patterns, and code style analysis. AI code gets stricter thresholds.",
    icon: GitMerge,
    accent: "#06b6d4",
    glow: "rgba(6,182,212,0.15)",
    tag: "FINGERPRINTING",
  },
];

function LayerCard({ layer, index }: { layer: typeof LAYERS[0]; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  const Icon = layer.icon;

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.15 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      className="glass glass-hover rounded-2xl p-6 flex flex-col gap-5 cursor-default"
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(24px)",
        transition: `opacity 0.5s ease ${index * 80}ms, transform 0.5s ease ${index * 80}ms`,
        boxShadow: visible ? `0 8px 40px ${layer.glow}, 0 0 0 1px rgba(255,255,255,0.03) inset` : undefined,
      }}
    >
      {/* Top row */}
      <div className="flex items-start justify-between">
        <div
          className="w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0"
          style={{ background: `${layer.accent}18`, border: `1px solid ${layer.accent}30` }}
        >
          <Icon className="w-5 h-5" style={{ color: layer.accent }} />
        </div>
        <div className="flex items-center gap-2">
          <span
            className="font-label text-[9px] px-2 py-1 rounded-full border"
            style={{ color: layer.accent, background: `${layer.accent}10`, borderColor: `${layer.accent}30` }}
          >
            {layer.tag}
          </span>
          <span className="font-mono text-[11px] text-zinc-700">{layer.number}</span>
        </div>
      </div>

      {/* Content */}
      <div>
        <h3 className="text-base font-bold text-zinc-100 mb-2">{layer.title}</h3>
        <p className="text-sm text-zinc-500 leading-relaxed">{layer.desc}</p>
      </div>

      {/* Bottom accent line */}
      <div
        className="h-px w-full rounded-full mt-auto"
        style={{ background: `linear-gradient(90deg, ${layer.accent}40, transparent)` }}
      />
    </div>
  );
}

export default function FeatureCards() {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.1 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section className="w-full max-w-7xl mx-auto px-6 py-24">
      {/* Section header */}
      <div
        ref={ref}
        className="text-center mb-16"
        style={{
          opacity: visible ? 1 : 0,
          transform: visible ? "translateY(0)" : "translateY(20px)",
          transition: "opacity 0.6s ease, transform 0.6s ease",
        }}
      >
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass border border-violet-500/20 mb-6">
          <Database className="w-3 h-3 text-violet-400" />
          <span className="font-label text-[10px] text-violet-300">5-LAYER DEFENSE ARCHITECTURE</span>
        </div>
        <h2 className="font-display text-4xl md:text-5xl text-white mb-4">
          Every AI commit.<br />
          <span className="text-gradient-cyber">5 layers of truth.</span>
        </h2>
        <p className="text-zinc-500 max-w-xl mx-auto leading-relaxed">
          Built specifically for the age of agentic coding. Each layer targets a different failure mode that existing tools completely miss.
        </p>
      </div>

      {/* Cards grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {LAYERS.map((layer, i) => (
          <LayerCard key={layer.number} layer={layer} index={i} />
        ))}

        {/* Trust Score formula card */}
        <div
          className="glass glass-hover rounded-2xl p-6 flex flex-col gap-4 md:col-span-2 lg:col-span-2"
          style={{
            opacity: visible ? 1 : 0,
            transform: visible ? "translateY(0)" : "translateY(24px)",
            transition: `opacity 0.5s ease ${5 * 80}ms, transform 0.5s ease ${5 * 80}ms`,
          }}
        >
          <div className="flex items-center gap-2">
            <Database className="w-4 h-4 text-cyan-400" />
            <span className="font-label text-[10px] text-cyan-400">COMPOSITE TRUST SCORE FORMULA</span>
          </div>
          <div className="code-block text-sm leading-relaxed">
            <span className="text-violet-300">TS</span>{" "}
            <span className="text-zinc-500">=</span>{" "}
            <span className="text-emerald-400">0.35</span>·Security{" "}
            <span className="text-zinc-500">+</span>{" "}
            <span className="text-emerald-400">0.30</span>·Architecture{" "}
            <span className="text-zinc-500">+</span>{" "}
            <span className="text-emerald-400">0.20</span>·BlastRadius{" "}
            <span className="text-zinc-500">+</span>{" "}
            <span className="text-emerald-400">0.10</span>·RejectedPatterns{" "}
            <span className="text-zinc-500">+</span>{" "}
            <span className="text-emerald-400">0.05</span>·AIOriginPenalty
          </div>
          <div className="grid grid-cols-4 gap-3 mt-2">
            {[
              { gate: "TRUSTED",  range: "≥ 0.85", color: "#10b981" },
              { gate: "REVIEW",   range: "≥ 0.65", color: "#f59e0b" },
              { gate: "CAUTION",  range: "≥ 0.40", color: "#f97316" },
              { gate: "BLOCK",    range: "< 0.40",  color: "#ef4444" },
            ].map(({ gate, range, color }) => (
              <div
                key={gate}
                className="rounded-xl p-3 text-center"
                style={{ background: `${color}0d`, border: `1px solid ${color}25` }}
              >
                <div className="font-display text-lg" style={{ color }}>{range}</div>
                <div className="font-label text-[9px] mt-1" style={{ color: `${color}aa` }}>{gate}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
